spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: "jdbc:oracle:thin:@localhost:1521:xe"
    username: "ensayos"
    password: "certificado"

  jpa:
    generate-ddl: true
    hibernate.ddl-auto: validate
    show-sql: true

server:
  port: 8084


